module.exports = {
  MYSQL: "jllgshllWEUJHGHYJkjsfjds30",
  TOKEN_SECRET: "11333COMEHOME",
  CLIENT_URL: "http://localhost:4000",
  RESET_PASSWORD_KEY: "11333COMEHOMEBACK",
  FAIL: "Failed",
  SUCCESS: "success",
  DEFAULT_SERVICE_STATUS: "Pending",
  DATA_SIGNUP: "Succesful, kindly activate your account",
  DATA_USER: "User Updated Succesfully",
  DATA_POLICYDETAIL: "Policy detail Updated Succesfully",
  DATA_LIST: "ServiceList Updated Succesfully",
  DATA_SIGNUP_EXIST: "Email already exists.",
  USER_NOT_FOUND: "Either username/password is incorrect",
  RATING_ADDED: "Rating succesfully added to the user",
  DATA_LOGIN_INVALID: "Invalid Password",
  INVALID_OTP: "Otp provided is invalid",
  PASSWORD_NOT_MATCH: "Password not matched",
  DATA_ACCOUNT_INACTIVE: "Account not active yet, kindly activate your account",
  DATA_ACCOUNT_ACTIVATED: "Great account activated successfully",
  PASSWORD_CHANGED: "Password changed successfully",
  PASSWORD_RESET: "Password reset successfully",
  RECORD_DELETED: "Record successfully deleted",
  OTP_SENT: "Otp sent to the registered email. Thank you",
  ACCOUNT_ALREADY_ACTIVE:
    "Your account is active already, please proceed to login",
  DATA_FAIL: "Email or Password does not match",
  DATA_OTP: "Otp not valid",
  DATA_WRONG: "Something went wrong",
  DATA_INVALID_NO: "Account with such credential not found",
  DATA_DELETED: "Deleted Successfully",
  DATA_INVALID: "Invalid Token",
  DATA_NO_TOKEN: "Unauthorized User, Provide Your Token",
  DATA_ALL: "All field are Required",
  USER_NOT_FOUND: "User with specified credentials not found",
  UPDATE_SUCCESSFUL: "Great record successfully updated",
  RECORD_NOT_FOUND: "Record with specified constraints not found",
  PRODUCT_NOT_FOUND: "Product with specified credentials not found",
  VEHICLE_NOT_FOUND: "Vehicle with specified credentials not found",
  POLICYDETAIL_NOT_FOUND: "Policy detail with specified credentials not found",
  PRODUCT_ADDED: "Product added successfully",
  INSURANCECOMPANY_ADDED: "Insurance company added successfully",
  VEHICLE_ADDED: "Vehicle added successfully",
  SERVICE_ADDED: "Service added successfully",
  POLICYDETAILS_ADDED: "Policy Details added successfully",
  PRODUCT_ADDED: "Product added successfully",
  SERVICELOG_ADDED: "ServiceLog added successfully",
  SERVICE_NOT_FOUND: "Service not available, kindly provide a valid record",
  SERVICE_REQUEST:
    "ServiceProviderId,  ServiceOwnerId and VehicleId are Require",
  POLICYDETAILS_REQUEST: "insuranceOwner and VehicleId are Require",
  SERVICELOG_REQUEST: "ServiceId and OwnerId are Require",
};
