module.exports = {
  MYSQL: "jllgshllWEUJHGHYJkjsfjds30",
  TOKEN_SECRET: "11333COMEHOME",
  CLIENT_URL: "http://localhost:4000",
  RESET_PASSWORD_KEY: "11333COMEHOMEBACK",
  FAIL: "failed",
  SUCCESS: "success",
  DATA_SIGNUP: "succesful, kindly activate your account",
  DATA_SIGNUP_EXIST: "Email already exists.",
  USER_NOT_FOUND: "Either username/password is incorrect",
  DATA_LOGIN_INVALID: "Invalid Password",
  INVALID_OTP: "Otp provided is invalid",
  PASSWORD_NOT_MATCH: "Password not matched",
  DATA_ACCOUNT_INACTIVE: "Account not active yet, kindly activate your account",
  DATA_ACCOUNT_ACTIVATED: "Great account activated successfully",
  PASSWORD_CHANGED: "Password changed successfully",
  PASSWORD_RESET: "Password reset successfully",
  OTP_SENT: "Otp sent to the registered email. Thank you",
  ACCOUNT_ALREADY_ACTIVE:
    "Your account is active already, please proceed to login",
  DATA_FAIL: "Email or Password does not match",
  DATA_OTP: "Otp not valid",
  DATA_WRONG: "Something went wrong",
  DATA_INVALID_NO: "Account with such credential not found",
  DATA_DELETED: "Deleted Successfully",
  DATA_INVALID: "Invalid Token",
  DATA_NO_TOKEN: "Unauthorized User, Provide Your Token",
  DATA_ALL: "All field are Required",
  USER_NOT_FOUND: "User with specified credentials not found",
  PRODUCT_NOT_FOUND: "Product with specified credentials not found",
  VEHICLE_NOT_FOUND: "Vehicle with specified credentials not found",
  PRODUCT_ADDED: "Product added successfully",
  VEHICLE_ADDED: "Vehicle added successfully",
  SERVICE_ADDED: "Service added successfully",
  SERVICELOG_ADDED: "ServiceLog added successfully",
};
